### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by lemmings189** [minecraft-py/minecraft#39]
### Operating System

Windows

### Python

pip 23.0.1

### Issue

$ python3 -m minecraft
[2023-03-22 20:59:11 INFO    ] ** Start Minecraft-in-python **
[2023-03-22 20:59:11 INFO    ] Operation system: Windows-10-10.0.19045-SP0
[2023-03-22 20:59:11 INFO    ] Python version: 3.10.10
[2023-03-22 20:59:11 INFO    ] Pyglet version: 2.0.5(OpenGL (4, 6))
[2023-03-22 20:59:11 INFO    ] Minecraft-in-python version: 0.0.1(data version: 1)
[2023-03-22 20:59:11 INFO    ] Create 256x256 texture atlas
[2023-03-22 20:59:11 ERROR   ] Game raise an error
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\Minecraft\minecraft\__main__.py", line 38, in start
    game.add_scene("minecraft:start", StartScene)
  File "C:\Users\admin\Desktop\Minecraft\minecraft\scene\__init__.py", line 65, in add_scene
    self.__scenes[name] = scene(*args, **kwargs)
  File "C:\Users\admin\Desktop\Minecraft\minecraft\scene\start.py", line 49, in __init__
    self._title_edition.position = (
  File "C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyglet\sprite.py", line 489, in position
    self._x, self._y, self._z = position
ValueError: not enough values to unpack (expected 3, got 2)
Stack (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\Desktop\Minecraft\minecraft\__main__.py", line 51, in <module>
    start()
  File "C:\Users\admin\Desktop\Minecraft\minecraft\__main__.py", line 44, in start
    logger.error("Game raise an error", exc_info=True, stack_info=True)

**Comment by jason-bowen-zheng** [comment]
@lemmings189 You are using pyglet 2.0.5 but the game was built on pyglet 1.5.\*.
